backend:
  name: git-gateway
  branch: main  # sesuaikan dengan branch lo

media_folder: "static/img"  # tempat upload gambar, buat folder ini kalau belum ada
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "about.html"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
