backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "proyek"
    label: "Proyek Terbaru"
    label_singular: "Proyek"
    files:
      - file: "data/proyek.yaml"
        label: "Daftar Proyek"
        name: "proyek"
        fields:
          - label: "Daftar Proyek"
            name: "items"
            widget: "list"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Deskripsi", name: "description", widget: "text" }
              - { label: "Gambar", name: "image", widget: "image" }
