backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "proyek"
    label: "Proyek Terbaru"
    label_singular: "Proyek"
    files:
      - file: "data/proyek.yaml"
        label: "Daftar Proyek"
        name: "proyek"
        fields:
          - label: "Daftar Proyek"
            name: "items"
            widget: "list"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Deskripsi", name: "description", widget: "text" }
              - { label: "Gambar", name: "image", widget: "image" }

- name: "hero"
    label: "Hero Slider"
    label_singular: "Slide"
    files:
      - file: "data/hero.yaml"
        label: "Daftar Slide"
        name: "hero"
        fields:
          - label: "Slides"
            name: "slides"
            widget: "list"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Deskripsi", name: "description", widget: "text" }
              - { label: "Tombol 1 - Teks", name: "button1_text", widget: "string" }
              - { label: "Tombol 1 - Link", name: "button1_link", widget: "string" }
              - { label: "Tombol 2 - Teks", name: "button2_text", widget: "string" }
              - { label: "Tombol 2 - Link", name: "button2_link", widget: "string" }
              - { label: "Gambar Latar", name: "background", widget: "image" }
